### ISSUE TITLE
ERROR : Unrecognized options for login request [400] 

### ISSUE THREAD

**Issue by Jayuda** [sujith3g/meteor-g-plus#12]
Hello Mr,...
i have error on login. i use this code : 

```
if (Meteor.isCordova) { // signIn through cordova
    Meteor.cordova_g_plus({
        cordova_g_plus: true,
        profile: ["email", "email_verified", "gender", "locale", "name", "picture"]
      }, function(error) {
            if (error) {
                alert(error);
            }
    });
}
```

But, show error on : " ERROR : Unrecognized options for login request [ 400] ". What shoud i do ?

![photo47534624019163559](https://cloud.githubusercontent.com/assets/1973447/12121584/90ab6ed4-b408-11e5-8989-336a56915acd.jpg)

**Comment by sujith3g** [comment]
@Jayuda  Any error messages in the server/client log ? I'm not able to re-create this error. Please provide more details about what version of `meteor`,`hedcet:cordova-google-plus-native-sign-in`,`android-sdk`,etc are you using.

**Comment by flake** [comment]
I too get the same signin error, with no log messages
ERROR : Unrecognized options for login request [400]

**Comment by sujith3g** [comment]
Please provide more details about what version of `meteor`,`hedcet:cordova-google-plus-native-sign-in`,`android-sdk`,etc are you using. I'm not able to recreate this error

**Comment by hedcet** [comment]
issue #10 might be helpful

**Comment by Jayuda** [comment]
Hello Mr. @sujith3g,
Detail version : 
*. Meteor 1.2.1
*. hedcet:cordova-google-plus-native-sign-in  added, version 1.1.0
*. Android SDK Tools 24.4.1

Source code project at : 
https://github.com/ThinkBuntu/SIWURE

Thanks for your help

**Comment by sujith3g** [comment]
Did you follow these [steps](https://github.com/sujith3g/meteor-g-plus#usage), I have updated step 4, where you have to submit your App ID(`com.siwure.thinkbuntu` in your case ) and SHA-1 of the key_store. I didn't see your App ID (`com.siwure.thinkbuntu`) OR `mobile-config.js` file in your [source code](https://github.com/ThinkBuntu/SIWURE)

**Comment by Jayuda** [comment]
Hello Mr,
I still have not found a way to fix this error.

SERVER SIDE : 

```
var google = {
    clientId: "XXXX",
    clientSecret: "XXXX"
};


Meteor.startup(function () {
    Accounts.loginServiceConfiguration.remove({
        service: "google"
    });

    Accounts.loginServiceConfiguration.insert({
        service: "google",
        clientId: google.clientId,
        secret: google.clientSecret
    });
});

```

ON CLIENT 

```
    'click a#loginGoogle': function (e, t) {
        e.preventDefault();
        if (Meteor.isCordova) {
            Meteor.cordova_g_plus({
                cordova_g_plus: true,
                profile: ["email", "email_verified", "gender", "locale", "name", "picture", "profile", "sub"]
            }, function (error) {
                if (error) alert(error);
            });
        } else {
            Meteor.loginWithGoogle(
                {
                    requestPermissions: [
                        'https://picasaweb.google.com/data/',
                        'https://www.googleapis.com/auth/userinfo.email',
                        'https://www.googleapis.com/auth/userinfo.profile',
                        'https://www.googleapis.com/auth/plus.me'
                    ],
                    requestOfflineToken: 'true'
                },
                Router.go('/')
            );
        }
    }
```

**Comment by Jayuda** [comment]
Sorry, This error because on server not install hedcet:cordova-google-plus-native-sign-in.
Thanks
