### ISSUE TITLE
How can we get this to seamlessly work with useraccounts?

### ISSUE THREAD

**Issue by elie222** [sujith3g/meteor-g-plus#14]
I use Ionic and would like to directly integrate this package into the login system without changing any of the login code. Will this work?

**Comment by sujith3g** [comment]
This package([`hedcet:cordova-google-plus-native-sign-in`](https://atmospherejs.com/hedcet/cordova-google-plus-native-sign-in)) is for [Meteor-cordova apps](http://docs.meteor.com/#/basic/buildingmobileapps), I haven't tried this package with `ionic`(by `ionic` What you mean is it just `ionic` OR `meteor-ionic` ?) . Feel free to report issues in using it.

If you are looking for a cordova plugin for gplus login, then [this](https://www.npmjs.com/package/cordova-plugin-googleplus) is it.

**Comment by elie222** [comment]
Yeah. I was specifically talking about meteoric and a cordova version of
it.

Was just wondering if it automatically hooks into the accounts core
packages or you have to hook it up yourself on cordova?

**Comment by sujith3g** [comment]
I don't know what is that you meant by "it automatically hooks into the accounts core
packages", 

[hedcet:cordova-google-plus-native-sign-in](https://atmospherejs.com/hedcet/cordova-google-plus-native-sign-in) package registers a new login method(`cordova_g_plus()`) with meteor Accounts, Which can be used like [this](https://github.com/sujith3g/meteor-g-plus/blob/master/client/meteor-g-plus.js#L17). This login method uses [`cordova-google-plus-plugin`](https://www.npmjs.com/package/cordova-plugin-googleplus) to verify the oauth token and then creates/updates the `Meteor.users`

**Comment by elie222** [comment]
I mean it integrates with the accounts ui packages. For example:
http://useraccounts-ionic.meteor.com/
You just an {{> atForm}} template to your app, and all the login stuff is
done automatically. If you've added the accounts-google package, it will
show a login with Google button.

**Comment by sujith3g** [comment]
Then you are searching for [cordova-google-plus-bootstrap](https://atmospherejs.com/hedcet/cordova-google-plus-bootstrap), still you have to follow the [steps](https://github.com/sujith3g/meteor-g-plus#usage) mentioned in the README of this repo

**Comment by elie222** [comment]
Thanks for the help
