### ISSUE TITLE
Targeting meteor release v1.1.0.3

### ISSUE THREAD

**Issue by mitesh-mutha** [sujith3g/meteor-g-plus#8]
I need to use your package for a meteor 1.1.0.3 project. However, when I follow the instructions and add the hedcet package and run android-device, i get the following error : Error: 404 Not Found: cordova-plugin-googleplus. 

Error while running for mobile platforms: Error running  
/home/mitesh/.meteor/packages/meteor-tool/.1.1.4.1o9xu8r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cordova-scripts/cordova.sh
Error: 404 Not Found: cordova-plugin-googleplus
at RegClient.<anonymous>
(/home/mitesh/.meteor/packages/meteor-tool/.1.1.4.1o9xu8r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:14)
at Request._callback
(/home/mitesh/.meteor/packages/meteor-tool/.1.1.4.1o9xu8r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
at Request.self.callback
(/home/mitesh/.meteor/packages/meteor-tool/.1.1.4.1o9xu8r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:236:22)
at Request.emit (events.js:98:17)
at Request.<anonymous>
(/home/mitesh/.meteor/packages/meteor-tool/.1.1.4.1o9xu8r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:1142:14)
at Request.emit (events.js:117:20)
at IncomingMessage.<anonymous>
(/home/mitesh/.meteor/packages/meteor-tool/.1.1.4.1o9xu8r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:1096:12)
at IncomingMessage.emit (events.js:117:20)
at _stream_readable.js:944:16
at process._tickCallback (node.js:442:13)

Fetching plugin "cordova-plugin-googleplus@4.0.3" via plugin registry

Could you tell me how I can solve the same ?

**Comment by hedcet** [comment]
@mitesh-mutha check version 0.0.15, i think it will work below MeteorJS-1.2
