### ISSUE TITLE
After Meteor run android - its showing following error

### ISSUE THREAD

**Issue by gauravbansal74** [sujith3g/meteor-g-plus#9]
Your system does not yet seem to fulfill all requirements to build apps for Android.

Please follow the installation instructions here:
https://github.com/meteor/meteor/wiki/Mobile-Development-Install:-Android-on-Linux

Specify the --verbose option to see more details about the status of individual requirements.

**Comment by sujith3g** [comment]
@gauravbansal74  This is something related to android sdk configurations, Make sure that Android sdk path is in your environment. 
For more details about this issue, Try to run it with `meteor run android --verbose`. 
[This](https://github.com/meteor/meteor/issues/5249#issuecomment-158759315) might be helpful.
